Forge support
RPMTW/era-connect pull request #14
Opened 2023-08-06 07:02 UTC by JustSimplyKyle

(the api of which how it calls needs to be improved, need ideas!)

2023-08-06 07:13 UTC, JustSimplyKyle commented
Now it currently panics with.
```dart
ERROR: Unhandled exception:
Unexpected shape of redirecting factory body: ReturnStatement: ReturnStatement(return <invalid:lib/api/gen/bridge_definitions.dart:176:7: Error: Redirection constructor target not found: 'Value_CompletedSetup'
ERROR: Target kernel_snapshot failed: Exception
Exception: Build process failed
```

2023-08-06 10:18 UTC, JustSimplyKyle commented
Now the api is much more good to use!

2023-08-12 14:33 UTC, SiongSng requested changes
感謝電神 :place_of_worship: :place_of_worship:

2023-08-12 14:33 UTC, SiongSng commented on app/lib/main.dart
> +    testRust();
測試用的程式碼麻煩先暫時 comment 起來，感謝。

2023-08-12 14:33 UTC, SiongSng commented on app/lib/main.dart
> +import 'package:era_connect/api/gen/bridge_definitions.dart' as bridge;
這些也需要 comment

2023-08-12 14:33 UTC, SiongSng commented on app/lib/api/config/lib.dart
> +// export 'config_api.dart';
```suggestion
export 'config_api.dart';
```

2023-08-12 14:33 UTC, SiongSng commented
我這邊主要先看 Dart 端的差異，與專案整體結構，Rust 的實做細節重構的時候我會順便 review，現在架構還不確定。

2023-08-13 04:44 UTC, SiongSng approved these changes
LGTM

2023-08-13 05:00 UTC, merged