refactor: move functions out of vanilla.rs
RPMTW/era-connect pull request #42
Opened 2023-08-28 03:28 UTC by JustSimplyKyle

2023-08-30 14:22 UTC, SiongSng requested changes

2023-08-30 14:22 UTC, SiongSng commented on app/native/src/api/vanilla/library.rs
> +    folder: RustOpaque<PathBuf>,
雖然與本 PR 無關，但好奇為何要以 RustOpaque 表示型別，這個 function 應該沒有直接在 Dart 端使用。

2023-08-30 14:35 UTC, JustSimplyKyle commented on app/native/src/api/vanilla/library.rs
> +    folder: RustOpaque<PathBuf>,
應該是不小心在剛開始開發遺留下來的
要開一個新的 pr 還是在這裡修就好了？

2023-09-02 13:55 UTC, SiongSng commented on app/native/src/api/vanilla/library.rs
> +    folder: RustOpaque<PathBuf>,
那在另外一個 PR 修好了，我先合併此 PR

2023-09-02 13:55 UTC, SiongSng approved these changes
LGTM

2023-09-02 13:55 UTC, merged